# Generated by Django 4.2.1 on 2024-11-05 18:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('medicamentos', '0001_initial'),
        ('alarmes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Receita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recomendacao', models.TextField(blank=True, help_text='Recomendações livres e adicionais sobre os medicamentos que foram receitados', null=True)),
                ('dose', models.CharField(help_text='Dosagem (Ex: 20mg / 1 comprimido / 20 gotas)', max_length=50)),
                ('alarme', models.OneToOneField(blank=True, help_text='Alarme para lembrar o paciente de tomar o medicamento', null=True, on_delete=django.db.models.deletion.CASCADE, to='alarmes.alarme')),
                ('medicamento', models.ForeignKey(help_text='Medicamento que foi receitado', on_delete=django.db.models.deletion.CASCADE, to='medicamentos.medicamento')),
            ],
        ),
    ]
