# Generated by Django 4.2.1 on 2024-11-26 14:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('receitas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='receita',
            name='medico',
            field=models.ForeignKey(help_text='Médico que irá prescrever a receita', on_delete=django.db.models.deletion.CASCADE, related_name='medico_receitas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='receita',
            name='paciente',
            field=models.ForeignKey(help_text='Paciente que irá receber a receita', on_delete=django.db.models.deletion.CASCADE, related_name='paciente_receitas', to=settings.AUTH_USER_MODEL),
        ),
    ]
