# Generated by Django 4.2.1 on 2024-12-03 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Medicamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Nome do medicamento', max_length=100)),
                ('dosagem', models.CharField(help_text='Dosagem do medicamento', max_length=100)),
                ('unidade', models.CharField(help_text='Unidade de dosagens do medicamento', max_length=100)),
                ('frequencia', models.CharField(help_text='Frequência de uso do medicamento', max_length=100)),
                ('data', models.DateField(help_text='Data de início do uso do medicamento')),
                ('alarme', models.BooleanField(default=False, help_text='Ativar alarme para o medicamento')),
                ('imagem', models.ImageField(blank=True, help_text='Imagem do medicamento', null=True, upload_to='medicamentos/')),
            ],
        ),
    ]
