# Generated by Django 4.2.1 on 2024-11-04 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Medicamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Nome do medicamento', max_length=100)),
                ('descricao', models.TextField(blank=True, help_text='Descrição do medicamento', null=True)),
            ],
        ),
    ]
