# Generated by Django 4.2.1 on 2024-11-19 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='user_type',
            field=models.CharField(choices=[('ADM', 'Administrador'), ('PAC', 'Paciente'), ('MED', 'Médico')], default='PAC', help_text='Tipo de usuário', max_length=3),
        ),
    ]
